#!/bin/bash

NAME_SCRIPT=$0
GET_OPTIONS=$1

if [ -z "$1" ]
  then
    echo "No argument supplied"
    echo "Choose: build, run or clean"
    exit 84
fi

# Checking if arguments are below 1

function check_args() {
    if [[ ${GET_OPTIONS} == "config" ]]; then
        rm -rf build/
        rm bomberman
        cmake -B ./build -DCMAKE_BUILD_TYPE=DEBUG
    fi
    if [[ ${GET_OPTIONS} == "build" ]]; then
        cmake --build ./build --config DEBUG
    fi
    if [[ ${GET_OPTIONS} == "all" ]]; then
        ./setup config
        ./setup build
    fi
    if [[ ${GET_OPTIONS} == "clean" ]]; then
        rm -rf build/
        rm bomberman
    fi
}

check_args